export const ActionTypes = {
    SET_AIRPORTS: "SET_AIRPORTS",
    SET_FLIGHT_RESULTS: "SET_FLIGHT_RESULTS",
    SET_SELECTED_FLIGHT_OFFER: "SET_SELECTED_FLIGHT_OFFER",
    SET_FLIGHT_REQUEST: "SET_FLIGHT_REQUEST"
};